module.exports.sampleReviews = [
    "Absolutely loved our stay here! The service was exceptional.",
    "Pretty decent spot for the price, but the room could have been cleaner.",
    "Terrible experience. The plumbing backed up and the staff was rude.",
    "A hidden gem! Quiet, comfortable beds, and close to everything.",
    "It was okay. Nothing spectacular, just your average highway roadside stop.",
    "Fantastic water pressure in the shower! Would definitely stay again.",
    "The walls were paper thin, but the continental breakfast made up for it.",
    "Just a great place for the kids. They loved the pool and the arcade.",
    "I was pleasantly surprised by the retro decor. Very nostalgic and fun.",
    "Not worth the money. The room smelled musty and the air conditioning was broken.",
    "The staff went above and beyond to make our stay comfortable. Highly recommend!",
    "A classic roadside motel experience. Clean, simple, and convenient for travelers.",
    "The neon sign outside is iconic! A great photo opportunity for road trippers.",
    "We had a wonderful stay. The beds were comfortable and the location was perfect.",
    "The breakfast was disappointing, but the room was spacious and well-maintained.",
    "Loved the vintage vibe of this place! It felt like stepping back in time.",
    "The parking lot was a bit crowded, but overall a good experience.",
    "The pool area was clean and well-kept. Perfect for a summer stay.",
    "I wouldn't recommend this place. The noise from the highway was unbearable.",
    "A charming little motel with friendly staff and a great location. We will be back for sure!",
    "The room was small, but the view of the sunset over the highway was breathtaking.",
    "The air conditioning was a lifesaver during our summer road trip. Very comfortable stay.",
    "The staff was very accommodating and helped us with local recommendations. Great service!",
    "The room had a strange odor, but the bed was surprisingly comfortable.",
    "A great place to rest after a long drive. Clean and efficient.",
    "The decor is a bit dated, but it adds to the charm of the motel.",
    "We had a lovely stay. The breakfast was simple but satisfying.",
    "The location is perfect for exploring the surrounding area. Highly recommend this motel.",
    "The room was clean and well-maintained, but the Wi-Fi was spotty at best.",
    "A fantastic roadside stop with a retro feel. We loved every minute of our stay.",
    "The staff was friendly and helpful, making our stay very enjoyable.",
    "The room was spacious and had all the amenities we needed for a comfortable stay.",
    "The motel has a great atmosphere and is perfect for a quick overnight stop.",
    "We had a wonderful experience. The staff was attentive and the room was clean.",
    "The location is convenient, but the noise from the highway can be a bit much.",
    "A great place to stay for travelers looking for a classic roadside experience.",
    "The beds were comfortable and the room was quiet, making for a restful night.",
    "The motel has a unique charm that makes it stand out from other roadside stops.",
    "We enjoyed our stay here. The staff was friendly and the room was clean.",
    "The breakfast options were limited, but the coffee was excellent.",
    "A solid choice for travelers looking for a budget-friendly option with character.",
    "The room had a nice view of the surrounding area, which made our stay more enjoyable.",
    "The staff went out of their way to make us feel welcome. We will definitely return.",
    "The motel has a great retro vibe that makes it a fun place to stay.",
    "We had a comfortable stay and appreciated the attention to detail in the room.",
];